#+TITLE: Dotfiles
#+PROPERTY: header-args :mkdirp yes

* Identity
Set name and e-mail.

#+BEGIN_SRC fundamental :noweb-ref name :exports none
  Nicolas De Jaeghere
#+END_SRC

#+BEGIN_SRC fundamental :noweb-ref e-mail :exports none
  nicolas@dejaeghe.re
#+END_SRC

#+BEGIN_SRC conf :tangle .config/environment.d/10-identity.conf :noweb yes
  NAME="<<name>>"
  EMAIL="<<e-mail>>"
#+END_SRC

* Well known directories
Set [[https://specifications.freedesktop.org/basedir-spec/][base directories]].

#+BEGIN_SRC conf :tangle .config/environment.d/10-base-dirs.conf
  XDG_CACHE_HOME="$HOME/.cache"
  XDG_CONFIG_HOME="$HOME/.config"
  XDG_DATA_HOME="$HOME/.local/share"
#+END_SRC

Then, set [[https://freedesktop.org/wiki/Software/xdg-user-dirs/][user directories]].

#+BEGIN_SRC conf :noweb-ref user-dirs :tangle .config/user-dirs.dirs
  XDG_DESKTOP_DIR="$HOME/.Bureaublad"
  XDG_DOCUMENTS_DIR="$HOME/Documenten"
  XDG_DOWNLOAD_DIR="$HOME/Inbox"
  XDG_MUSIC_DIR="$HOME/Muziek"
  XDG_PICTURES_DIR="$HOME/Afbeeldingen"
  XDG_PUBLICSHARE_DIR="$HOME/Delen"
  XDG_TEMPLATES_DIR="$HOME/Sjablonen"
  XDG_VIDEOS_DIR="$HOME/Video's"
#+END_SRC

Again, but as environment variables.

#+BEGIN_SRC conf :tangle .config/environment.d/10-user-dirs.conf :noweb yes
  <<user-dirs>>
#+END_SRC

Finally, set other directories.

#+BEGIN_SRC conf :tangle .config/environment.d/11-koek-dirs.conf
  KOEK_CALENDARS_DIR="$XDG_DOCUMENTS_DIR/Kalenders"
  KOEK_EMAIL_DIR="$XDG_DOCUMENTS_DIR/E-mail"
  KOEK_NEWS_DIR="$XDG_DOCUMENTS_DIR/Nieuws"
  KOEK_PROJECTS_DIR="$HOME/Projecten"
#+END_SRC

* E-mail

** isync
:PROPERTIES:
:header-args+: :tangle .config/isync/mbsyncrc
:END:

Store =.mbsyncstate= with maildir sub directories, simplifying backup.

#+BEGIN_SRC fundamental
  SyncState *
#+END_SRC

*** Personal account
To configure the domain, follow [[https://www.fastmail.com/help/receive/domains-setup-nsmx.html][Configuring your domain with NS/MX
(FastMail)]].

To create the maildir directory, run:

#+BEGIN_SRC sh :tangle no
  mkdir -p ~/Documenten/E-mail/Personal
#+END_SRC

Define local personal store.

#+BEGIN_SRC fundamental
  MaildirStore personal-local
  Inbox "~/Documenten/E-mail/Personal/INBOX/"
  Path "~/Documenten/E-mail/Personal/"
  SubFolders Verbatim
#+END_SRC

To generate the app password, follow [[https://www.fastmail.com/help/clients/apppassword.html][App Passwords (FastMail)]]. Name it
=Emacs e-mail= and give it access to IMAP and SMTP. Then, to store it
securely, run:

#+BEGIN_SRC sh :tangle no
  secret-tool store --label="Emacs e-mail personal (IMAP)" host "imap.fastmail.com" port "993" user "nicolas@dejaeghe.re"
  secret-tool store --label="Emacs e-mail personal (SMTP)" host "smtp.fastmail.com" port "465" user "nicolas@dejaeghe.re"
#+END_SRC

Define remote personal store. For server details, see [[https://www.fastmail.com/help/technical/servernamesandports.html][Server names and
ports (FastMail)]].

#+BEGIN_SRC fundamental
  IMAPStore personal-remote
  Host imap.fastmail.com
  SSLType IMAPS
  User nicolas@dejaeghe.re
  PassCmd "secret-tool lookup host \"imap.fastmail.com\" port \"993\" user \"nicolas@dejaeghe.re\""
#+END_SRC

Define personal channel.

#+BEGIN_SRC fundamental
  Channel personal
  Master :personal-remote:
  Slave :personal-local:
  Patterns *
  Sync All
  Create Both
  Remove Both
  Expunge Both
  CopyArrivalDate yes
#+END_SRC

** mu
Move data and maildir directory out of the way.

#+BEGIN_SRC conf :tangle .config/environment.d/50-mu.conf
  MU_HOME="$XDG_DATA_HOME/mu"
  MAILDIR="$KOEK_EMAIL_DIR"
#+END_SRC

To create the initial index, run:

#+BEGIN_SRC sh
  mbsync -c "$XDG_CONFIG_HOME/isync/mbsyncrc" -a && mu index
#+END_SRC

* Firefox

** Saka Key
[[https://addons.mozilla.org/en-US/firefox/addon/saka-key/][Saka Key (Firefox Add-ons)]]

Create a new profile. Change:

#+CAPTION: General
| Name                              | Value |
|-----------------------------------+-------|
| Saka Key enabled                  | Yes   |
| Prevent pages from stealing focus | Yes   |
| Automatically activate hint       | Yes   |
| Detect hints using cursor style   | No    |
| Smooth scroll                     | No    |
| Scroll step                       | 32    |

#+CAPTION: Keybindings
| Name                          | Value     |
|-------------------------------+-----------|
| Bind to physical keys         | No        |
| Ignore modifier keys          | No        |
| Hint characters               | qsdfjklm  |
| Open link                     | j j       |
| Open link in background tab   | j C-o     |
| Open link in foreground tab   | j o       |
| Open link in new window       | j m       |
| Open link in incognito window | j C-m     |
| Download link                 | j d       |
| Focus input                   | j i       |
| Go back                       | l         |
| Go forward                    | r         |
| Go up                         | u         |
| Go to root                    | U         |
| Scroll down                   | n         |
| Scroll up                     | p         |
| Scroll page down              | SPC       |
| Scroll page up                | DEL       |
| Scroll half page down         | <next>    |
| Scroll half page up           | <prior>   |
| Scroll to bottom              | M->       |
| Scroll to top                 | M-<       |
| New tab                       | o         |
| Restore tab                   | M-o       |
| Duplicate tab                 | C-o       |
| New window                    | m         |
| New incognito window          | C-m       |
| Close tab                     | d         |
| Close other tabs              | C-d       |
| Refresh tab                   | g         |
| Hard refresh tab              | G         |
| Move tab new window           | M-m       |
| Pass one key to page          | k         |
| Pass all keys to page         | C-k       |
| Stop passing keys to page     | C-j       |
| Copy current URL              | M-w       |

** uBlock Origin
[[https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/][uBlock Origin (Firefox Add-ons)]]

Keep the defaults.

** Video Downloader Professional
[[https://addons.mozilla.org/en-US/firefox/addon/video-downloader-profession/][Video Downloader Professional (Firefox Add-ons)]]

Keep the defaults.

* FreeCAD
Ensure FreeCAD's packages are found.

#+BEGIN_SRC conf :tangle .config/environment.d/50-freecad.conf
  PYTHONPATH="/usr/lib/freecad/lib"${PYTHONPATH:+:$PYTHONPATH}
#+END_SRC

* Git
Set identity.

#+BEGIN_SRC conf :tangle .config/git/config :noweb yes
  [user]
  name = <<name>>
  email = <<e-mail>>
#+END_SRC

** Global ignore
Ignore common artifacts. For pattern format, see ~man 5 gitignore~.

#+BEGIN_SRC fundamental :tangle .config/git/ignore
  .shadow-cljs/
  build/
  node_modules/
  .nrepl-port
#+END_SRC

* GNOME Shell

** App folders
To apply configuration, run:

#+BEGIN_SRC sh
  gnome-catgen -s
#+END_SRC

*** Citrix
#+BEGIN_SRC fundamental :tangle .local/share/applications-categories/Citrix.category
  Citrix_subscribed_XD-C10-S01-Controller.DLG-SB2206-PRD-PROD $S1048-1056.desktop
  Citrix_subscribed_XD-C10-S01-Controller.VDI Dedicated Default Office 20 $P9447.desktop
  wfcmgr.desktop
#+END_SRC

*** Creative
#+BEGIN_SRC fundamental :tangle .local/share/applications-categories/Creative.category
  ardour.desktop
  blender.desktop
  calf.desktop
  freecad.desktop
  gimp.desktop
  inkscape.desktop
  openscad.desktop
  org.fontforge.FontForge.desktop
  scribus.desktop
  tape.desktop
  valentina.desktop
#+END_SRC

*** DisplayCAL
#+BEGIN_SRC fundamental :tangle .local/share/applications-categories/DisplayCAL.category
  displaycal-3dlut-maker.desktop
  displaycal-apply-profiles.desktop
  displaycal-curve-viewer.desktop
  displaycal-profile-info.desktop
  displaycal-scripting-client.desktop
  displaycal-synthprofile.desktop
  displaycal-testchart-editor.desktop
  displaycal-vrml-to-x3d-converter.desktop
  displaycal.desktop
#+END_SRC

*** Internet
#+BEGIN_SRC fundamental :tangle .local/share/applications-categories/Internet.category
  chromium.desktop
  firefox.desktop
  io.github.qtox.qTox.desktop
  jami-gnome.desktop
  jdownloader.desktop
#+END_SRC

*** Leisure
#+BEGIN_SRC fundamental :tangle .local/share/applications-categories/Leisure.category
  makemkv.desktop
  org.gnome.Lollypop.desktop
  org.musicbrainz.Picard.desktop
  puddletag.desktop
  steam-native.desktop
  vlc.desktop
#+END_SRC

*** LibreOffice
#+BEGIN_SRC fundamental :tangle .local/share/applications-categories/LibreOffice.category
  libreoffice-base.desktop
  libreoffice-calc.desktop
  libreoffice-draw.desktop
  libreoffice-impress.desktop
  libreoffice-math.desktop
  libreoffice-startcenter.desktop
  libreoffice-writer.desktop
#+END_SRC

*** System
#+BEGIN_SRC fundamental :tangle .local/share/applications-categories/System.category
  ca.desrt.dconf-editor.desktop
  gnome-control-center.desktop
  gnome-system-monitor.desktop
  gufw.desktop
  org.gnome.DiskUtility.desktop
  org.gnome.Logs.desktop
  org.gnome.Terminal.desktop
  org.gnome.font-viewer.desktop
  org.gnome.seahorse.Application.desktop
  org.gnome.tweaks.desktop
  yelp.desktop
#+END_SRC

*** Utilities
#+BEGIN_SRC fundamental :tangle .local/share/applications-categories/Utilities.category
  com.obsproject.Studio.desktop
  eid-viewer.desktop
  electrum.desktop
  org.gnome.Cheese.desktop
  org.gnome.Evince.desktop
  org.gnome.FileRoller.desktop
  org.gnome.Nautilus.desktop
  org.gnome.Screenshot.desktop
  org.gnome.eog.desktop
  org.keepassxc.KeePassXC.desktop
  simple-scan.desktop
  syncthing-gtk.desktop
#+END_SRC

*** Work
#+BEGIN_SRC fundamental :tangle .local/share/applications-categories/Work.category
  arduino.desktop
  emacs.desktop
  org.gnome.Boxes.desktop
  org.gnome.Calculator.desktop
  org.gnome.Maps.desktop
  org.gnome.Weather.desktop
  org.gnome.clocks.desktop
  org.octave.Octave.desktop
  wireshark.desktop
  wolfram-mathematica11.desktop
#+END_SRC

** Superfluous applications
Hide superfluous applications.

#+BEGIN_SRC conf :tangle .local/share/applications/assistant.desktop
  [Desktop Entry]
  NoDisplay=true
#+END_SRC

#+BEGIN_SRC conf :tangle .local/share/applications/avahi-discover.desktop
  [Desktop Entry]
  NoDisplay=true
#+END_SRC

#+BEGIN_SRC conf :tangle .local/share/applications/bssh.desktop
  [Desktop Entry]
  NoDisplay=true
#+END_SRC

#+BEGIN_SRC conf :tangle .local/share/applications/bvnc.desktop
  [Desktop Entry]
  NoDisplay=true
#+END_SRC

#+BEGIN_SRC conf :tangle .local/share/applications/cmake-gui.desktop
  [Desktop Entry]
  NoDisplay=true
#+END_SRC

#+BEGIN_SRC conf :tangle .local/share/applications/configmgr.desktop
  [Desktop Entry]
  NoDisplay=true
#+END_SRC

#+BEGIN_SRC conf :tangle .local/share/applications/conncentre.desktop
  [Desktop Entry]
  NoDisplay=true
#+END_SRC

#+BEGIN_SRC conf :tangle .local/share/applications/cups.desktop
  [Desktop Entry]
  NoDisplay=true
#+END_SRC

#+BEGIN_SRC conf :tangle .local/share/applications/designer.desktop
  [Desktop Entry]
  NoDisplay=true
#+END_SRC

#+BEGIN_SRC conf :tangle .local/share/applications/ipython.desktop
  [Desktop Entry]
  NoDisplay=true
#+END_SRC

#+BEGIN_SRC conf :tangle .local/share/applications/jconsole-java-openjdk.desktop
  [Desktop Entry]
  NoDisplay=true
#+END_SRC

#+BEGIN_SRC conf :tangle .local/share/applications/jshell-java-openjdk.desktop
  [Desktop Entry]
  NoDisplay=true
#+END_SRC

#+BEGIN_SRC conf :tangle .local/share/applications/linguist.desktop
  [Desktop Entry]
  NoDisplay=true
#+END_SRC

#+BEGIN_SRC conf :tangle .local/share/applications/lstopo.desktop
  [Desktop Entry]
  NoDisplay=true
#+END_SRC

#+BEGIN_SRC conf :tangle .local/share/applications/org.gnome.Extensions.desktop
  [Desktop Entry]
  NoDisplay=true
#+END_SRC

#+BEGIN_SRC conf :tangle .local/share/applications/qdbusviewer.desktop
  [Desktop Entry]
  NoDisplay=true
#+END_SRC

#+BEGIN_SRC conf :tangle .local/share/applications/qv4l2.desktop
  [Desktop Entry]
  NoDisplay=true
#+END_SRC

#+BEGIN_SRC conf :tangle .local/share/applications/qvidcap.desktop
  [Desktop Entry]
  NoDisplay=true
#+END_SRC

#+BEGIN_SRC conf :tangle .local/share/applications/steam.desktop
  [Desktop Entry]
  NoDisplay=true
#+END_SRC

#+BEGIN_SRC conf :tangle .local/share/applications/xdvi.desktop
  [Desktop Entry]
  NoDisplay=true
#+END_SRC

* Jupyter Notebook
Move configuration directory out of the way.

#+BEGIN_SRC conf :tangle .config/environment.d/50-jupyter.conf
  JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"
#+END_SRC

Documentation on configuring the frontend is [[https://jupyter-notebook.readthedocs.io/en/stable/frontend_config.html#persisting-configuration-settings][limited]]. For properties,
see [[https://codemirror.net/doc/manual.html#config][User manual and reference guide - Configuration (CodeMirror)]].

#+BEGIN_SRC json :tangle .config/jupyter/nbconfig/notebook.json
  {
      "CodeCell": {
          "cm_config": {
              "cursorBlinkRate": 0
          }
      },
      "MarkdownCell": {
          "cm_config": {
              "cursorBlinkRate": 0
          }
      }
  }
#+END_SRC

* NLTK
Move data directory out of the way.

#+BEGIN_SRC conf :tangle .config/environment.d/50-nltk.conf
  NLTK_DATA="$XDG_DATA_HOME/nltk"
#+END_SRC

* Steam
Show Steam with native runtime as Steam.

#+BEGIN_SRC conf :tangle .local/share/applications/steam-native.desktop
  [Desktop Entry]
  Name=Steam
  Comment=Application for managing and playing games on Steam
  Exec=/usr/bin/steam-native %U
  Icon=steam
  Terminal=false
  Type=Application
  Categories=Network;FileTransfer;Game;
  MimeType=x-scheme-handler/steam;
  Actions=Store;Community;Library;Servers;Screenshots;News;Settings;BigPicture;Friends;
  StartupWMClass=Steam

  [Desktop Action Store]
  Name=Store
  Exec=steam steam://store

  [Desktop Action Community]
  Name=Community
  Exec=steam steam://url/SteamIDControlPage

  [Desktop Action Library]
  Name=Library
  Exec=steam steam://open/games

  [Desktop Action Servers]
  Name=Servers
  Exec=steam steam://open/servers

  [Desktop Action Screenshots]
  Name=Screenshots
  Exec=steam steam://open/screenshots

  [Desktop Action News]
  Name=News
  Exec=steam steam://open/news

  [Desktop Action Settings]
  Name=Settings
  Exec=steam steam://open/settings

  [Desktop Action BigPicture]
  Name=Big Picture
  Exec=steam steam://open/bigpicture

  [Desktop Action Friends]
  Name=Friends
  Exec=steam steam://open/friends
#+END_SRC
