#+TITLE: Dotfiles
#+PROPERTY: header-args :mkdirp yes

#+BEGIN_QUOTE
Thou shalt not pollute your neighbor's ~/ -- Exodus 20:17
#+END_QUOTE

* Identity
Set name and e-mail.

#+BEGIN_SRC fundamental :noweb-ref name :exports none
  Nicolas De Jaeghere
#+END_SRC

#+BEGIN_SRC fundamental :noweb-ref email :exports none
  nicolas@dejaeghe.re
#+END_SRC

#+BEGIN_SRC conf :tangle env/.config/environment.d/10-identity.conf :noweb yes
  NAME="<<name>>"
  EMAIL="<<email>>"
#+END_SRC

* Well known directories
Set [[https://freedesktop.org/wiki/Specifications/basedir-spec/][base directories]].

#+BEGIN_SRC conf :tangle xdg/.config/environment.d/10-base-dirs.conf
  XDG_CACHE_HOME="$HOME/.cache"
  XDG_CONFIG_HOME="$HOME/.config"
  XDG_DATA_HOME="$HOME/.local/share"
#+END_SRC

Then, set [[https://freedesktop.org/wiki/Software/xdg-user-dirs/][user directories]].

#+BEGIN_SRC conf :noweb-ref user-dirs :tangle xdg/.config/user-dirs.dirs
  XDG_DESKTOP_DIR="$HOME/.Bureaublad"
  XDG_DOCUMENTS_DIR="$HOME/Documenten"
  XDG_DOWNLOAD_DIR="$HOME/Inbox"
  XDG_MUSIC_DIR="$HOME/Muziek"
  XDG_PICTURES_DIR="$HOME/Afbeeldingen"
  XDG_PUBLICSHARE_DIR="$HOME/Delen"
  XDG_TEMPLATES_DIR="$HOME/Sjablonen"
  XDG_VIDEOS_DIR="$HOME/Video's"
#+END_SRC

Again, but as environment variables.

#+BEGIN_SRC conf :tangle xdg/.config/environment.d/10-user-dirs.conf :noweb yes
  <<user-dirs>>
#+END_SRC

Finally, set other directories.

#+BEGIN_SRC conf :tangle env/.config/environment.d/11-koek-dirs.conf
  KOEK_CALENDARS_DIR="$XDG_DOCUMENTS_DIR/Kalenders"
  KOEK_CONTACTS_DIR="$XDG_DOCUMENTS_DIR/Contacten"
  KOEK_EMAIL_DIR="$XDG_DOCUMENTS_DIR/E-mail"
  KOEK_NEWS_DIR="$XDG_DOCUMENTS_DIR/Nieuws"
  KOEK_NOTES_DIR="$XDG_DOCUMENTS_DIR/Notities"
  KOEK_PROJECTS_DIR="$HOME/Projecten"
#+END_SRC

* Superfluous applications
Hide superfluous applications.

#+BEGIN_SRC conf :noweb-ref desktop-nodisplay :exports none
  [Desktop Entry]
  Type=Application
  NoDisplay=true
#+END_SRC

#+BEGIN_SRC conf :tangle qt/.local/share/applications/assistant.desktop :noweb yes
  <<desktop-nodisplay>>
  Name=Qt Assistant
#+END_SRC

#+BEGIN_SRC conf :tangle avahi/.local/share/applications/avahi-discover.desktop :noweb yes
  <<desktop-nodisplay>>
  Name=Avahi Zeroconf Browser
#+END_SRC

#+BEGIN_SRC conf :tangle avahi/.local/share/applications/bssh.desktop :noweb yes
  <<desktop-nodisplay>>
  Name=Avahi SSH Server Browser
#+END_SRC

#+BEGIN_SRC conf :tangle avahi/.local/share/applications/bvnc.desktop :noweb yes
  <<desktop-nodisplay>>
  Name=Avahi VNC Server Browser
#+END_SRC

#+BEGIN_SRC conf :tangle cmake/.local/share/applications/cmake-gui.desktop :noweb yes
  <<desktop-nodisplay>>
  Name=CMake
#+END_SRC

#+BEGIN_SRC conf :tangle cups/.local/share/applications/cups.desktop :noweb yes
  <<desktop-nodisplay>>
  Name=Manage Printing
#+END_SRC

#+BEGIN_SRC conf :tangle qt/.local/share/applications/designer.desktop :noweb yes
  <<desktop-nodisplay>>
  Name=Qt Designer
#+END_SRC

#+BEGIN_SRC conf :tangle jupyter/.local/share/applications/ipython.desktop :noweb yes
  <<desktop-nodisplay>>
  Name=ipython
#+END_SRC

#+BEGIN_SRC conf :tangle java/.local/share/applications/jconsole-java-openjdk.desktop :noweb yes
  <<desktop-nodisplay>>
  Name=OpenJDK Java Console
#+END_SRC

#+BEGIN_SRC conf :tangle java/.local/share/applications/jshell-java-openjdk.desktop :noweb yes
  <<desktop-nodisplay>>
  Name=OpenJDK Java Shell
#+END_SRC

#+BEGIN_SRC conf :tangle qt/.local/share/applications/linguist.desktop :noweb yes
  <<desktop-nodisplay>>
  Name=Qt Linguist
#+END_SRC

#+BEGIN_SRC conf :tangle hwloc/.local/share/applications/lstopo.desktop :noweb yes
  <<desktop-nodisplay>>
  Name=Hardware Locality lstopo
#+END_SRC

#+BEGIN_SRC conf :tangle gnome/.local/share/applications/org.gnome.Extensions.desktop :noweb yes
  <<desktop-nodisplay>>
  Name=Extensions
#+END_SRC

#+BEGIN_SRC conf :tangle qt/.local/share/applications/qdbusviewer.desktop :noweb yes
  <<desktop-nodisplay>>
  Name=Qt QDbusViewer
#+END_SRC

#+BEGIN_SRC conf :tangle qt/.local/share/applications/qv4l2.desktop :noweb yes
  <<desktop-nodisplay>>
  Name=Qt V4L2 test utility
#+END_SRC

#+BEGIN_SRC conf :tangle qt/.local/share/applications/qvidcap.desktop :noweb yes
  <<desktop-nodisplay>>
  Name=Qt V4L2 video capture utility
#+END_SRC

#+BEGIN_SRC conf :tangle steam/.local/share/applications/steam.desktop :noweb yes
  <<desktop-nodisplay>>
  Name=Steam (Runtime)
#+END_SRC

#+BEGIN_SRC conf :tangle tex/.local/share/applications/xdvi.desktop :noweb yes
  <<desktop-nodisplay>>
  Name=XDvi
#+END_SRC

* GNOME catgen                                                        :setup:
To apply configuration, run:

#+BEGIN_SRC sh
  gnome-catgen -s
#+END_SRC

** Creative
#+BEGIN_SRC fundamental :tangle catgen/.local/share/applications-categories/Creative.category
  ardour.desktop
  blender.desktop
  calf.desktop
  freecad.desktop
  gimp.desktop
  openscad.desktop
  org.fontforge.FontForge.desktop
  org.inkscape.Inkscape.desktop
  scribus.desktop
  tape.desktop
  valentina.desktop
#+END_SRC

** DisplayCAL
#+BEGIN_SRC fundamental :tangle catgen/.local/share/applications-categories/DisplayCAL.category
  displaycal-3dlut-maker.desktop
  displaycal-apply-profiles.desktop
  displaycal-curve-viewer.desktop
  displaycal-profile-info.desktop
  displaycal-scripting-client.desktop
  displaycal-synthprofile.desktop
  displaycal-testchart-editor.desktop
  displaycal-vrml-to-x3d-converter.desktop
  displaycal.desktop
#+END_SRC

** Internet
#+BEGIN_SRC fundamental :tangle catgen/.local/share/applications-categories/Internet.category
  chromium.desktop
  firefox.desktop
  io.github.qtox.qTox.desktop
  jami-gnome.desktop
#+END_SRC

** Leisure
#+BEGIN_SRC fundamental :tangle catgen/.local/share/applications-categories/Leisure.category
  makemkv.desktop
  org.gnome.Lollypop.desktop
  org.musicbrainz.Picard.desktop
  puddletag.desktop
  steam-native.desktop
  vlc.desktop
#+END_SRC

** LibreOffice
#+BEGIN_SRC fundamental :tangle catgen/.local/share/applications-categories/LibreOffice.category
  libreoffice-base.desktop
  libreoffice-calc.desktop
  libreoffice-draw.desktop
  libreoffice-impress.desktop
  libreoffice-math.desktop
  libreoffice-startcenter.desktop
  libreoffice-writer.desktop
#+END_SRC

** System
#+BEGIN_SRC fundamental :tangle catgen/.local/share/applications-categories/System.category
  ca.desrt.dconf-editor.desktop
  gnome-control-center.desktop
  gnome-system-monitor.desktop
  gufw.desktop
  org.gnome.DiskUtility.desktop
  org.gnome.Logs.desktop
  org.gnome.Terminal.desktop
  org.gnome.font-viewer.desktop
  org.gnome.seahorse.Application.desktop
  org.gnome.tweaks.desktop
  yelp.desktop
#+END_SRC

** Utilities
#+BEGIN_SRC fundamental :tangle catgen/.local/share/applications-categories/Utilities.category
  com.obsproject.Studio.desktop
  eid-viewer.desktop
  electrum.desktop
  org.gnome.Cheese.desktop
  org.gnome.Evince.desktop
  org.gnome.FileRoller.desktop
  org.gnome.Nautilus.desktop
  org.gnome.Screenshot.desktop
  org.gnome.eog.desktop
  org.keepassxc.KeePassXC.desktop
  simple-scan.desktop
  syncthing-gtk.desktop
#+END_SRC

** Work
#+BEGIN_SRC fundamental :tangle catgen/.local/share/applications-categories/Work.category
  arduino.desktop
  emacs.desktop
  org.gnome.Boxes.desktop
  org.gnome.Calculator.desktop
  org.gnome.Maps.desktop
  org.gnome.Weather.desktop
  org.gnome.clocks.desktop
  org.octave.Octave.desktop
  wireshark.desktop
  wolfram-mathematica11.desktop
#+END_SRC

* Bash                                                                  :wip:

** Login
:PROPERTIES:
:header-args+: :tangle bash/.profile
:END:

Interactive and non interactive

#+BEGIN_SRC sh
  export PATH="$HOME/.local/bin"${PATH:+:$PATH}
#+END_SRC

#+BEGIN_SRC sh
  [[ -f ~/.bashrc ]] && . ~/.bashrc
#+END_SRC

** Interactive
:PROPERTIES:
:header-args+: :tangle bash/.bashrc
:END:

Non login

#+BEGIN_SRC sh
  [[ $- != *i* ]] && return
#+END_SRC

#+BEGIN_SRC sh
  export HISTFILE="$XDG_DATA_HOME/bash/history"
#+END_SRC

#+BEGIN_SRC sh
  alias ls='ls -lah --color=auto'
#+END_SRC

#+BEGIN_SRC sh
  PS1='[\u@\h \W]\$ '
#+END_SRC

* Stow
Set target directory.

#+BEGIN_SRC fundamental :tangle .stowrc
  --target=~/
#+END_SRC

* Syncthing                                                           :setup:
Stores:
- archive: Archief
- documents: Bureaublad, Documenten, Inbox and Projecten
- documents-extra: Boeken, Sjablonen and Varia
- music: Muziek and Podcasts
- pictures: Afbeeldingen
- share: Delen
- video: Video's

To stow all stores, run:

#+BEGIN_SRC sh
  stow -d ~/.ststore/ -t ~/ archive documents documents-extra music pictures share video
#+END_SRC

* Git
Set identity.

#+BEGIN_SRC conf :tangle git/.config/git/config :noweb yes
  [user]
  name = <<name>>
  email = <<email>>
#+END_SRC

** Global ignore
Ignore common artifacts. For pattern format, see ~man 5 gitignore~.

#+BEGIN_SRC fundamental :tangle git/.config/git/ignore
  .shadow-cljs/
  build/
  node_modules/
  .nrepl-port
#+END_SRC

* GnuPG
Move data directory out of the way.

#+BEGIN_SRC conf :tangle gnupg/.config/environment.d/50-gnupg.conf
  GNUPGHOME="$XDG_DATA_HOME/gnupg"
#+END_SRC

* Firefox

** Saka Key
[[https://addons.mozilla.org/en-US/firefox/addon/saka-key/][Saka Key (Firefox Add-ons)]]

Create a new profile. Change:

#+CAPTION: General
| Name                              | Value |
|-----------------------------------+-------|
| Saka Key enabled                  | Yes   |
| Prevent pages from stealing focus | Yes   |
| Automatically activate hint       | Yes   |
| Detect hints using cursor style   | No    |
| Smooth scroll                     | No    |
| Scroll step                       | 32    |

#+CAPTION: Keybindings
| Name                          | Value    | Name                  | Value     | Name                      | Value |
|-------------------------------+----------+-----------------------+-----------+---------------------------+-------|
| Bind to physical keys         | No       | Go up                 | =u=       | Duplicate tab             | =C-o= |
| Ignore modifier keys          | No       | Go to root            | =U=       | New window                | =m=   |
| Hint characters               | qsdfjklm | Scroll down           | =n=       | New incognito window      | =C-m= |
| Open link                     | =j j=    | Scroll up             | =p=       | Close tab                 | =d=   |
| Open link in background tab   | =j C-o=  | Scroll page down      | =SPC=     | Close other tabs          | =C-d= |
| Open link in foreground tab   | =j o=    | Scroll page up        | =DEL=     | Refresh tab               | =g=   |
| Open link in new window       | =j m=    | Scroll half page down | =<next>=  | Hard refresh tab          | =G=   |
| Open link in incognito window | =j C-m=  | Scroll half page up   | =<prior>= | Move tab new window       | =M-m= |
| Download link                 | =j d=    | Scroll to bottom      | =M->=     | Pass one key to page      | =k=   |
| Focus input                   | =j i=    | Scroll to top         | =M-<=     | Pass all keys to page     | =C-k= |
| Go back                       | =l=      | New tab               | =o=       | Stop passing keys to page | =C-j= |
| Go forward                    | =r=      | Restore tab           | =M-o=     | Copy current URL          | =M-w= |

#+CAPTION: Blacklist
#+BEGIN_SRC fundamental
  ^http://localhost:8888/notebooks/
#+END_SRC

** uBlock Origin
[[https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/][uBlock Origin (Firefox Add-ons)]]

Keep defaults.

** Video Downloader Professional
[[https://addons.mozilla.org/en-US/firefox/addon/video-downloader-profession/][Video Downloader Professional (Firefox Add-ons)]]

Keep defaults.

* E-mail

** isync
:PROPERTIES:
:header-args+: :tangle isync/.config/isync/mbsyncrc
:END:

Store sync state with maildir sub directories, simplifying backup.

#+BEGIN_SRC conf
  SyncState *
#+END_SRC

*** Personal account                                                  :setup:
To configure the domain, follow [[https://www.fastmail.com/help/receive/domains-setup-nsmx.html][Configuring your domain with NS/MX
(FastMail)]].

To create the maildir directory, run:

#+BEGIN_SRC sh :tangle no
  mkdir -p "$KOEK_EMAIL_DIR/Personal"
#+END_SRC

Define local personal store. Only tilde is expanded, not environment
variables.

#+BEGIN_SRC conf
  MaildirStore personal_local
  Path "~/Documenten/E-mail/Personal/"
  Inbox "~/Documenten/E-mail/Personal/INBOX/"
  SubFolders Verbatim
#+END_SRC

To generate the app password, follow [[https://www.fastmail.com/help/clients/apppassword.html][App Passwords (FastMail)]]. Name it
=Emacs e-mail= and give it access to IMAP and SMTP. Then, to store it
securely, run:

#+BEGIN_SRC sh :tangle no
  secret-tool store --label="Emacs e-mail personal (IMAP)" host "imap.fastmail.com" port "993" user "nicolas@dejaeghe.re"
  secret-tool store --label="Emacs e-mail personal (SMTP)" host "smtp.fastmail.com" port "465" user "nicolas@dejaeghe.re"
#+END_SRC

Define remote personal store. For server details, see [[https://www.fastmail.com/help/technical/servernamesandports.html][Server names and
ports (FastMail)]].

#+BEGIN_SRC conf
  IMAPStore personal_remote
  Host imap.fastmail.com
  SSLType IMAPS
  User nicolas@dejaeghe.re
  PassCmd "secret-tool lookup host \"imap.fastmail.com\" port \"993\" user \"nicolas@dejaeghe.re\""
#+END_SRC

Define personal channel.

#+BEGIN_SRC conf
  Channel personal
  Master :personal_remote:
  Slave :personal_local:
  Patterns *
  Sync All
  Create Both
  Remove Both
  Expunge Both
  CopyArrivalDate yes
#+END_SRC

** mu                                                                 :setup:
Move maildir directory out of the way.

#+BEGIN_SRC conf :tangle mu/.config/environment.d/50-mu.conf
  MAILDIR="$KOEK_EMAIL_DIR"
#+END_SRC

To create the database, run:

#+BEGIN_SRC sh :noweb yes
  mbsync -c "$XDG_CONFIG_HOME/isync/mbsyncrc" -a && mu init --my-address="nicolas@dejaeghe.re" --my-address="nicodeja@gmail.com" --my-address="nicodeja@mac.com" --my-address="Nicolas.DeJaeghere@belfius.be"
#+END_SRC

* vdirsyncer
:PROPERTIES:
:header-args+: :tangle vdirsyncer/.config/vdirsyncer/config
:END:

Store sync state with vdir directories, simplifying backup. Only tilde
is expanded, not environment variables.

#+BEGIN_SRC conf
  [general]
  status_path = "~/Documenten/Contacten/.vdirsyncer/"
#+END_SRC

** Personal account                                                   :setup:
To create the vdir directory, run:

#+BEGIN_SRC sh :tangle no
  mkdir -p "$KOEK_CONTACTS_DIR/Personal"
#+END_SRC

Define local personal storage.

#+BEGIN_SRC conf
  [storage personal_local]
  type = "filesystem"
  path = "~/Documenten/Contacten/Personal/"
  fileext = ".vcf"
#+END_SRC

To generate the app password, follow [[https://www.fastmail.com/help/clients/apppassword.html][App Passwords (FastMail)]]. Name it
=Emacs contacts= and give it access to CardDAV. Then, to store it
securely, run:

#+BEGIN_SRC sh :tangle no
  secret-tool store --label="Emacs contacts personal" host "carddav.fastmail.com:443" port "https" user "nicolas@dejaeghe.re"
#+END_SRC

Define remote personal storage. For server details, see [[https://www.fastmail.com/help/technical/servernamesandports.html][Server names
and ports (FastMail)]].

#+BEGIN_SRC conf
  [storage personal_remote]
  type = "carddav"
  url = "https://carddav.fastmail.com/"
  username = "nicolas@dejaeghe.re"
  password.fetch = ["command", "secret-tool", "lookup", "host", "carddav.fastmail.com:443", "port", "https", "user", "nicolas@dejaeghe.re"]
#+END_SRC

Define personal pair.

#+BEGIN_SRC conf
  [pair personal]
  a = "personal_remote"
  b = "personal_local"
  collections = ["from a", "from b"]
#+END_SRC

To create the collections, run:

#+BEGIN_SRC sh :tangle no
  vdirsyncer discover && vdirsyncer sync
#+END_SRC

* FreeCAD
Ensure FreeCAD's packages are found.

#+BEGIN_SRC conf :tangle freecad/.config/environment.d/50-freecad.conf
  PYTHONPATH="/usr/lib/freecad/lib"${PYTHONPATH:+:$PYTHONPATH}
#+END_SRC

* Steam
Show Steam with native runtime as Steam.

#+BEGIN_SRC conf :tangle steam/.local/share/applications/steam-native.desktop
  [Desktop Entry]
  Name=Steam
  Comment=Application for managing and playing games on Steam
  Exec=/usr/bin/steam-native %U
  Icon=steam
  Terminal=false
  Type=Application
  Categories=Network;FileTransfer;Game;
  MimeType=x-scheme-handler/steam;
  Actions=Store;Community;Library;Servers;Screenshots;News;Settings;BigPicture;Friends;
  StartupWMClass=Steam

  [Desktop Action Store]
  Name=Store
  Exec=steam steam://store

  [Desktop Action Community]
  Name=Community
  Exec=steam steam://url/SteamIDControlPage

  [Desktop Action Library]
  Name=Library
  Exec=steam steam://open/games

  [Desktop Action Servers]
  Name=Servers
  Exec=steam steam://open/servers

  [Desktop Action Screenshots]
  Name=Screenshots
  Exec=steam steam://open/screenshots

  [Desktop Action News]
  Name=News
  Exec=steam steam://open/news

  [Desktop Action Settings]
  Name=Settings
  Exec=steam steam://open/settings

  [Desktop Action BigPicture]
  Name=Big Picture
  Exec=steam steam://open/bigpicture

  [Desktop Action Friends]
  Name=Friends
  Exec=steam steam://open/friends
#+END_SRC

* Org protocol                                                        :setup:
Define org protocol scheme handler. Must invoke a shell to expand
environment variables. For desktop entry or scheme handler format, see
[[https://freedesktop.org/wiki/Specifications/desktop-entry-spec/][Desktop Entry Specification (freedesktop)]] respectively [[https://freedesktop.org/wiki/Specifications/shared-mime-info-spec/][Shared MIME
Info Specification (freedesktop)]].

#+BEGIN_SRC conf :tangle emacs/.local/share/applications/org-protocol.desktop
  [Desktop Entry]
  Type=Application
  Name=org-protocol
  Icon=emacs
  TryExec=emacsclient
  Exec=sh -c "emacsclient -s \"\\$XDG_RUNTIME_DIR/emacs\" %u"
  Terminal=false
  MimeType=x-scheme-handler/org-protocol;
  NoDisplay=true
#+END_SRC

To register the scheme handler, run:

#+BEGIN_SRC sh
  update-desktop-database ~/.local/share/applications
#+END_SRC

* Jupyter Notebook
Move configuration directory out of the way.

#+BEGIN_SRC conf :tangle jupyter/.config/environment.d/50-jupyter.conf
  JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"
#+END_SRC

Documentation on configuring the frontend is [[https://jupyter-notebook.readthedocs.io/en/stable/frontend_config.html#persisting-configuration-settings][limited]]. For properties,
see [[https://codemirror.net/doc/manual.html#config][User manual and reference guide - Configuration (CodeMirror)]].

#+BEGIN_SRC json :tangle jupyter/.config/jupyter/nbconfig/notebook.json
  {
      "CodeCell": {
          "cm_config": {
              "cursorBlinkRate": 0
          }
      },
      "MarkdownCell": {
          "cm_config": {
              "cursorBlinkRate": 0
          }
      }
  }
#+END_SRC

** IPython
Move configuration directory out of the way.

#+BEGIN_SRC conf :tangle jupyter/.config/environment.d/50-ipython.conf
  IPYTHONDIR="$XDG_CONFIG_HOME/ipython"
#+END_SRC

* CUDA
Move cache directory out of the way.

#+BEGIN_SRC conf :tangle cuda/.config/environment.d/50-cuda.conf
  CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv/ComputeCache"
#+END_SRC

* Keras
Move configuration directory out of the way.

#+BEGIN_SRC conf :tangle keras/.config/environment.d/50-keras.conf
  KERAS_HOME="$XDG_CONFIG_DIR/keras"
#+END_SRC

* NLTK
Move data directory out of the way.

#+BEGIN_SRC conf :tangle nltk/.config/environment.d/50-nltk.conf
  NLTK_DATA="$XDG_DATA_HOME/nltk"
#+END_SRC
