#+TITLE: Dotfiles

[[https://en.wikipedia.org/wiki/Hidden_file_and_hidden_directory][Dotfiles]], configuration worth saving.

* The work-in-progress branch
Development occurs on the =wip= branch. As additions mature, they're
added to the =master= branch. =wip= is *force pushed* to and ordinarily far
ahead of =master=.

* For the curious
Take a look at [[file:dotfiles.org][dotfiles.org]] and [[file:emacs.org][emacs.org]]. Everything else is the
result of [[info:org#Extracting source code][tangling]].

* For the masochist
To get started, run:

#+BEGIN_SRC sh
  git clone https://github.com/Koekelas/dotfiles.git
#+END_SRC

Then, to [[https://www.gnu.org/software/stow/][stow]] all packages, run from this directory:

#+BEGIN_SRC sh
  make install
#+END_SRC

Finally, take a look at [[file:dotfiles.org::*Identity][Identity]], [[file:dotfiles.org::*Well known directories][Well known directories]], [[file:emacs.org::*Personal][Personal]] and
all headings tagged =setup=. To apply changes, run =M-x= ~org-babel-tangle~
from the changed file and restart the changed application or re-login.

** Installing dependencies
Git is mandatory, everything else is optional.

- General:
  - [[https://git-scm.com/][Git]]
  - [[https://github.com/BurntSushi/ripgrep][ripgrep]]
  - [[https://hunspell.github.io/][Hunspell]]
  - [[https://x.org/][xprop]] (set GTK theme variant)
  - [[https://www.fsd.it/shop/fonts/pragmatapro/][PragmataPro]] or [[https://typeof.net/Iosevka/][Iosevka]] (fixed pitch font)
  - [[https://www.ibm.com/plex/][IBM Plex]] (variable pitch font)
- X window manager:
  - [[https://github.com/Koekelas/exwm-gdm][exwm-gdm]]
  - [[https://x.org/][xset]]
  - [[https://github.com/yshui/picom][picom]]
  - [[https://github.com/derat/xsettingsd][xsettingsd]]
  - [[https://x.org/][xsetroot]] and [[https://github.com/Airblader/unclutter-xfixes][unclutter]]
  - [[https://www.argyllcms.com/][ArgyllCMS]] (dispwin, load color profile)
  - [[https://github.com/linuxwacom/xf86-input-wacom][xf86-input-wacom]] (xsetwacom, setup tablet)
- Terminal emulator: [[https://cmake.org/][CMake]], [[https://www.gnu.org/software/libtool/][libtool]] and [[https://github.com/neovim/libvterm][libvterm]]
- E-mail client: [[http://isync.sourceforge.net/][isync]] and [[https://www.djcbsoftware.nl/code/mu/][mu]]
- Address book: [[https://github.com/pimutils/vdirsyncer][vdirsyncer]]
- News reader: [[https://curl.haxx.se/][curl]]
- PDF viewer: [[https://poppler.freedesktop.org/][poppler]], [[http://www.libpng.org/][libpng]], [[https://www.zlib.net/][zlib]] and [[https://imagemagick.org/][ImageMagick]]
- Media player: [[https://mpv.io/][mpv]] and [[https://github.com/yt-dlp/yt-dlp][yt-dlp]]
- C family:
  - [[https://gcc.gnu.org/][GCC]]
  - [[https://mesonbuild.com/][Meson]]
  - [[https://clang.llvm.org/][Clang]] (language server)
  - [[https://www.gnu.org/software/gdb/][GDB]]
  - [[https://www.arduino.cc/en/Main/Software][Arduino IDE]]
- Clojure and ClojureScript (depends on Java and JavaScript):
  - [[https://leiningen.org/][Leiningen]]
  - [[https://github.com/clj-kondo/clj-kondo][clj-kondo]]
- Common Lisp: [[http://www.sbcl.org/][Steel Bank Common Lisp]]
- Erlang:
  - [[https://www.erlang.org/][Erlang/OTP]]
  - [[https://www.rebar3.org/][Rebar3]]
  - [[https://erlang-ls.github.io/][Erlang LS]]
- Java:
  - [[https://www.oracle.com/technetwork/java/javase/downloads/index.html][Java SE JDK]]
  - [[https://maven.apache.org/][Apache Maven]]
  - [[https://projects.eclipse.org/projects/eclipse.jdt.ls][Eclipse JDT Language Server]]
- JavaScript:
  - [[https://nodejs.org/][Node.js]]
  - [[https://github.com/theia-ide/typescript-language-server][TypeScript Language Server]]
  - [[https://github.com/NicolasPetton/Indium][Indium]]
- Octave and MATLAB: [[https://www.gnu.org/software/octave/][Octave]]
- OpenSCAD: [[https://www.openscad.org/][OpenSCAD]]
- Python:
  - [[https://www.python.org/][Python]]
  - [[https://pipenv.pypa.io/][Pipenv]]
  - [[https://github.com/python-lsp/python-lsp-server][Python LSP Server]]
- Scheme: [[https://www.gnu.org/software/guile/][Guile]]
- SQL: [[https://www.postgresql.org/][PostgreSQL]]
- TeX, Org and Markdown:
  - [[https://www.latex-project.org/][LaTeX]]
  - [[https://pandoc.org/][pandoc]]
- Wolfram Language: [[https://www.wolfram.com/mathematica/][Mathematica]]

To install dependencies on [[https://www.archlinux.org/][Arch Linux]], run:

#+BEGIN_SRC sh
  ## General
  pacman -S git ripgrep hunspell hunspell-en_us xorg-xprop ttf-ibm-plex ttc-iosevka
  # Install PragmataPro from source

  ## X window manager
  pacman -S xorg-xset picom xsettingsd xorg-xsetroot unclutter argyllcms xf86-input-wacom
  # Install exwm-gdm from source

  ## Terminal emulator
  pacman -S cmake libtool libvterm

  ## E-mail client
  pacman -S isync
  # Install mu from AUR

  ## Address book
  pacman -S vdirsyncer

  ## News reader
  pacman -S curl

  ## PDF viewer
  pacman -S poppler-glib libpng zlib imagemagick

  ## Media player
  pacman -S mpv youtube-dl

  ## C family
  pacman -S gcc meson clang gdb arduino arduino-avr-core

  # Setup Arduino
  gpasswd -a $(whoami) uucp

  ## Clojure and ClojureScript
  pacman -S leiningen
  # Install clj-kondo-bin from AUR

  ## Common Lisp
  pacman -S sbcl

  ## Erlang
  pacman -S erlang-nox
  # Install rebar3 and erlang_ls from AUR

  ## Java
  pacman -S jdk-openjdk maven
  # Install jdtls from AUR

  ## JavaScript
  pacman -S nodejs npm typescript-language-server
  npm i -g indium

  ## Octave and MATLAB
  pacman -S octave

  ## OpenSCAD
  pacman -S openscad

  ## Python
  pacman -S python python-pipenv python-lsp-server python-rope python-pyflakes

  ## Scheme
  pacman -S guile

  ## SQL
  pacman -S postgresql

  # Setup PostgreSQL
  sudo -u postgres initdb -D /var/lib/postgres/data/
  systemctl enable postgresql.service
  systemctl start postgresql.service
  sudo -u postgres createuser -s $(whoami)
  createdb

  ## TeX, Org and Markdown
  pacman -S texlive-core texlive-latexextra pandoc

  ## Wolfram Language
  # Install mathematica from AUR
#+END_SRC
