;;; belgian-holidays-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from belgian-holidays.el

(register-definition-prefixes "belgian-holidays" '("holiday-belgian-"))

;;; End of scraped data

(provide 'belgian-holidays-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; belgian-holidays-autoloads.el ends here
